### ISSUE TITLE
Specify mutable/immutable

### ISSUE THREAD

**Issue by XenonPy** [almostDemoPy/demo.py#3]
For lists, sets, etc, it should specify whether they can be modified or not. Just a small change. This is a pretty common error, where users will get some code with an immutable datatype in it and try to modify it.

**Comment by almostDemoPy** [comment]
will make a separate file for this, thanks

**Comment by almostDemoPy** [comment]
@XenonPy i've appended brief descriptions for now. if you'd like to request for a clarification on something, let me know and maybe i'll add it in the future
